version: "3.4"
services:
  node:
    build: 
      context: ./
      target: base-github
      dockerfile: ./.devcontainer/base.dockerfile
    env_file: .env
    volumes:
      - ./:/usr/src/app
      - local_lib:/usr/local/lib
      - node_modules:/usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
      - "5000:5000"
      - "8080:8080"
    entrypoint: ["/bin/sh"]
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  node_modules:
    driver: local
  local_lib:
    driver: local
  